const STORAGE_KEY="countdown-v8",THEME_KEY="countdown-theme-v8",$=id=>document.getElementById(id);
const list=$("countdownList"),dialog=$("countdownDialog"),form=$("countdownForm"),titleInput=$("titleInput"),dateInput=$("dateInput"),timeInput=$("timeInput"),categoryInput=$("categoryInput");
let editingId=null,activeDetailId=null,deferredPrompt=null,shareItem=null,shareStyle="enthousiast";
let countdowns=JSON.parse(localStorage.getItem(STORAGE_KEY)||"null")||[{id:crypto.randomUUID(),title:"vakantie",category:"vakantie",target:"2026-05-13T16:00:00"},{id:crypto.randomUUID(),title:"verjaardag",category:"verjaardag",target:"2026-09-11T16:00:00"}];
const emojiMap={vakantie:"✈️",liefde:"❤️",verjaardag:"🎂",feest:"🎉",deadline:"⏳",anders:"⭐"};
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(countdowns))}function pad(n){return String(Math.max(0,n)).padStart(2,"0")}
function fmt(t){return new Intl.DateTimeFormat("nl-NL",{day:"numeric",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(t)).replace(".","")}
function calc(t){let d=Math.max(0,new Date(t)-Date.now()),days=Math.floor(d/864e5);d%=864e5;let h=Math.floor(d/36e5);d%=36e5;let m=Math.floor(d/6e4);d%=6e4;let s=Math.floor(d/1e3);return{days,h,m,s,done:new Date(t)<=Date.now()}}
function unit(l,v){let x=l==="DAGEN"?String(v).padStart(3,"0"):pad(v);return`<div class="unit"><div class="label">${l}</div><div class="digits">${x}</div></div>`}
function render(){list.innerHTML="";[...countdowns].sort((a,b)=>new Date(a.target)-new Date(b.target)).forEach(item=>{let t=calc(item.target),em=emojiMap[item.category]||"⭐",card=document.createElement("article");card.className="card";card.dataset.id=item.id;card.innerHTML=`<section class="display"><div class="card-head"><div class="card-title">${em} ${item.title}</div><div class="card-icons">⏰↩⌃</div></div><div class="timer">${unit("DAGEN",t.days)}${unit("UUR",t.h)}${unit("MIN",t.m)}${unit("SEC",t.s)}</div></section><footer class="card-foot"><span>${fmt(item.target)}</span><div class="actions"><button class="action-btn" data-share="${item.id}">📲</button><button class="action-btn" data-cal="${item.id}">📅</button><button class="action-btn" data-edit="${item.id}">✎</button><button class="action-btn" data-del="${item.id}">🗑</button></div></footer>`;list.appendChild(card)})}
function openForm(item=null){editingId=item?.id||null;titleInput.value=item?.title||"";categoryInput.value=item?.category||"vakantie";if(item){let d=new Date(item.target);dateInput.value=d.toISOString().slice(0,10);timeInput.value=d.toTimeString().slice(0,5)}else{let d=new Date(Date.now()+864e5);dateInput.value=d.toISOString().slice(0,10);timeInput.value="16:00"}dialog.showModal()}
$("addBtn").onclick=()=>openForm();$("cancelBtn").onclick=()=>dialog.close();
form.onsubmit=e=>{e.preventDefault();let data={id:editingId||crypto.randomUUID(),title:titleInput.value,category:categoryInput.value,target:`${dateInput.value}T${timeInput.value}:00`,confettiShown:false};countdowns=editingId?countdowns.map(i=>i.id===editingId?{...i,...data}:i):[...countdowns,data];save();dialog.close();render()};
function comma(v){return v.toFixed(1).replace(".",",")}function workdays(s,e){let c=0,d=new Date(s),end=new Date(e);d.setHours(0,0,0,0);end.setHours(0,0,0,0);while(d<end){let day=d.getDay();if(day&&day!==6)c++;d.setDate(d.getDate()+1)}return c}
function detail(id){activeDetailId=id;let item=countdowns.find(x=>x.id===id),t=calc(item.target),diff=Math.max(0,new Date(item.target)-Date.now()),days=diff/864e5,em=emojiMap[item.category]||"⭐";$("detailContent").innerHTML=`<article class="detail-count-card"><div class="card-head"><div class="card-title">${em} ${item.title}</div><div class="card-icons">⏰↩⌃</div></div><div class="timer">${unit("DAGEN",t.days)}${unit("UUR",t.h)}${unit("MIN",t.m)}${unit("SEC",t.s)}</div></article><div class="detail-date">${fmt(item.target)}</div><div class="detail-buttons"><button class="detail-btn" onclick="openShare('${item.id}')">📲 WhatsApp</button><button class="detail-btn" onclick="addCalendar('${item.id}')">📅 Agenda</button></div><section class="stats">${[["JAREN",comma(days/365.2425)],["MAANDEN",comma(days/30.436875)],["WEKEN",comma(days/7)],["DAGEN",comma(days)],["Werkdagen",comma(workdays(new Date(),new Date(item.target)))],["UREN",Math.floor(diff/36e5)],["MINUTEN",Math.floor(diff/6e4)],["SECONDEN",Math.floor(diff/1e3)],["MILLISECONDS",diff]].map((r,i)=>`<div class="stat-row ${i>5?"stat-strip":""}"><span class="stat-label">${r[0]}</span><span class="stat-value">${r[1]}</span></div>`).join("")}</section>`;$("detailDialog").showModal()}
list.onclick=e=>{if(e.target.dataset.edit){openForm(countdowns.find(x=>x.id===e.target.dataset.edit));return}if(e.target.dataset.del){countdowns=countdowns.filter(x=>x.id!==e.target.dataset.del);save();render();return}if(e.target.dataset.share){openShare(e.target.dataset.share);return}if(e.target.dataset.cal){addCalendar(e.target.dataset.cal);return}let c=e.target.closest(".card");if(c)detail(c.dataset.id)}
$("backDetailBtn").onclick=()=>$("detailDialog").close();$("detailEditBtn").onclick=()=>{let item=countdowns.find(x=>x.id===activeDetailId);$("detailDialog").close();openForm(item)};$("detailShareBtn").onclick=()=>openShare(activeDetailId);
function shareMessage(item,style){let t=calc(item.target),em=emojiMap[item.category]||"⭐",url=location.origin+location.pathname;if(t.done)return`🎊 Het is zover!\n\nVandaag is het moment:\n${em} ${item.title}\n\nEindelijk! 😄\n\n${url}`;let base=`Nog ${t.days} dagen, ${t.h} uur en ${t.m} minuten tot:\n\n${em} ${item.title}\n\n📅 ${fmt(item.target)}`;let end={enthousiast:"Ik kan echt niet wachten 😄🔥",romantisch:"Ik kijk hier zó naar uit ❤️",grappig:"De spanning is niet meer te houden 😂",simpel:"Even delen zodat je het weet ✅"}[style];return`🎉 Countdown update!\n\n${base}\n\n${end}\n\nBekijk de countdown:\n${url}`}
window.openShare=function(id){shareItem=countdowns.find(x=>x.id===id);shareStyle="enthousiast";$("shareText").value=shareMessage(shareItem,shareStyle);$("shareDialog").showModal()}
document.querySelectorAll("[data-style]").forEach(b=>b.onclick=()=>{shareStyle=b.dataset.style;$("shareText").value=shareMessage(shareItem,shareStyle)});
$("copyShareBtn").onclick=async()=>{await navigator.clipboard.writeText($("shareText").value);alert("Tekst gekopieerd")};$("openWhatsAppBtn").onclick=()=>{location.href=`https://wa.me/?text=${encodeURIComponent($("shareText").value)}`};$("closeShareBtn").onclick=()=>$("shareDialog").close();
window.addCalendar=function(id){let item=countdowns.find(x=>x.id===id),start=new Date(item.target),end=new Date(start.getTime()+3600000),f=d=>d.toISOString().replace(/[-:]/g,"").split(".")[0]+"Z";let ics=`BEGIN:VCALENDAR\nVERSION:2.0\nBEGIN:VEVENT\nSUMMARY:${item.title}\nDESCRIPTION:Final Countdown PRO\nDTSTART:${f(start)}\nDTEND:${f(end)}\nEND:VEVENT\nEND:VCALENDAR`;let blob=new Blob([ics],{type:"text/calendar"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`${item.title.replace(/[^a-z0-9]/gi,"-")}.ics`;a.click();URL.revokeObjectURL(a.href)}
function setTheme(theme){document.body.className=theme==="neon"?"":`theme-${theme}`;localStorage.setItem(THEME_KEY,theme)}setTheme(localStorage.getItem(THEME_KEY)||"neon");$("themeBtn").onclick=()=>$("themeDialog").showModal();document.querySelectorAll("[data-theme]").forEach(b=>b.onclick=()=>{setTheme(b.dataset.theme);$("themeDialog").close()});$("closeThemeBtn").onclick=()=>$("themeDialog").close();
function confetti(){let c=$("confettiCanvas"),ctx=c.getContext("2d");c.width=innerWidth;c.height=innerHeight;let p=Array.from({length:140},()=>({x:Math.random()*c.width,y:-20*Math.random(),r:3+Math.random()*6,v:2+Math.random()*5,a:Math.random()*6})),colors=["#ff1010","#ffd166","#06d6a0","#4cc9f0","#ff4fd8"],start=Date.now();(function frame(){ctx.clearRect(0,0,c.width,c.height);p.forEach((q,i)=>{q.y+=q.v;q.x+=Math.sin(q.a+=.08)*2;ctx.fillStyle=colors[i%colors.length];ctx.fillRect(q.x,q.y,q.r,q.r)});if(Date.now()-start<3500)requestAnimationFrame(frame);else ctx.clearRect(0,0,c.width,c.height)})();}
function checkDone(){let changed=false;countdowns.forEach(i=>{if(new Date(i.target)<=Date.now()&&!i.confettiShown){i.confettiShown=true;changed=true;confetti();navigator.vibrate?.([120,70,120]);alert(`🎉 Het is zover: ${i.title}!`)}});if(changed)save()}
$("menuBtn").onclick=()=>alert("Final Countdown PRO v8");window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;$("installBtn").hidden=false;$("installStatus").textContent="Klaar om te installeren."});$("installBtn").onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$("installBtn").hidden=true}};if("serviceWorker"in navigator){navigator.serviceWorker.register("./sw.js",{scope:"./"}).catch(()=>{})}render();setInterval(()=>{render();checkDone()},1000);setInterval(()=>{if(activeDetailId&&$("detailDialog").open)detail(activeDetailId)},1000);